site_name: aiida-atomistic, the materials science plugin for the AiiDA platform
theme:
  name: readthedocs
  font:
    text: Roboto
  features:
    - header.autohide
    - navigation.tabs
    - navigation.sections

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - User guide: source/user_guide.md
  - Developer guide: source/developer_guide/core_developer_guide_structuredata.md
